// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoBuff.proto

package BuffProto;

public interface MensagemPong1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:protoBuff.MensagemPong1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mensagemPong1 = 1;</code>
   * @return The mensagemPong1.
   */
  java.lang.String getMensagemPong1();
  /**
   * <code>string mensagemPong1 = 1;</code>
   * @return The bytes for mensagemPong1.
   */
  com.google.protobuf.ByteString
      getMensagemPong1Bytes();
}
