// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoBuff.proto

package BuffProto;

public interface MensagemPong2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:protoBuff.MensagemPong2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mensagemPong2 = 1;</code>
   * @return The mensagemPong2.
   */
  java.lang.String getMensagemPong2();
  /**
   * <code>string mensagemPong2 = 1;</code>
   * @return The bytes for mensagemPong2.
   */
  com.google.protobuf.ByteString
      getMensagemPong2Bytes();
}
