// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoBuff.proto

package BuffProto;

public interface MensagemPing3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:protoBuff.MensagemPing3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mensagemPing3 = 1;</code>
   * @return The mensagemPing3.
   */
  java.lang.String getMensagemPing3();
  /**
   * <code>string mensagemPing3 = 1;</code>
   * @return The bytes for mensagemPing3.
   */
  com.google.protobuf.ByteString
      getMensagemPing3Bytes();
}
