// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoBuff.proto

package BuffProto;

public interface MensagemPong3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:protoBuff.MensagemPong3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mensagemPong3 = 1;</code>
   * @return The mensagemPong3.
   */
  java.lang.String getMensagemPong3();
  /**
   * <code>string mensagemPong3 = 1;</code>
   * @return The bytes for mensagemPong3.
   */
  com.google.protobuf.ByteString
      getMensagemPong3Bytes();
}
