// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoBuff.proto

package BuffProto;

public interface MensagemPing2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:protoBuff.MensagemPing2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mensagemPing2 = 1;</code>
   * @return The mensagemPing2.
   */
  java.lang.String getMensagemPing2();
  /**
   * <code>string mensagemPing2 = 1;</code>
   * @return The bytes for mensagemPing2.
   */
  com.google.protobuf.ByteString
      getMensagemPing2Bytes();
}
