// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoBuff.proto

package BuffProto;

public interface MensagemPing1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:protoBuff.MensagemPing1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mensagemPing1 = 1;</code>
   * @return The mensagemPing1.
   */
  java.lang.String getMensagemPing1();
  /**
   * <code>string mensagemPing1 = 1;</code>
   * @return The bytes for mensagemPing1.
   */
  com.google.protobuf.ByteString
      getMensagemPing1Bytes();
}
