// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoBuff.proto

package BuffProto;

public final class ProtoBuff {
  private ProtoBuff() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoBuff_MensagemPing1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoBuff_MensagemPing1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoBuff_MensagemPing2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoBuff_MensagemPing2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoBuff_MensagemPing3_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoBuff_MensagemPing3_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoBuff_MensagemPong1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoBuff_MensagemPong1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoBuff_MensagemPong2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoBuff_MensagemPong2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoBuff_MensagemPong3_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoBuff_MensagemPong3_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ProtoBuff.proto\022\tprotoBuff\"&\n\rMensagem" +
      "Ping1\022\025\n\rmensagemPing1\030\001 \001(\t\"&\n\rMensagem" +
      "Ping2\022\025\n\rmensagemPing2\030\001 \001(\t\"&\n\rMensagem" +
      "Ping3\022\025\n\rmensagemPing3\030\001 \001(\t\"&\n\rMensagem" +
      "Pong1\022\025\n\rmensagemPong1\030\001 \001(\t\"&\n\rMensagem" +
      "Pong2\022\025\n\rmensagemPong2\030\001 \001(\t\"&\n\rMensagem" +
      "Pong3\022\025\n\rmensagemPong3\030\001 \001(\tB\030\n\tBuffProt" +
      "oB\tProtoBuffP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protoBuff_MensagemPing1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protoBuff_MensagemPing1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoBuff_MensagemPing1_descriptor,
        new java.lang.String[] { "MensagemPing1", });
    internal_static_protoBuff_MensagemPing2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protoBuff_MensagemPing2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoBuff_MensagemPing2_descriptor,
        new java.lang.String[] { "MensagemPing2", });
    internal_static_protoBuff_MensagemPing3_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protoBuff_MensagemPing3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoBuff_MensagemPing3_descriptor,
        new java.lang.String[] { "MensagemPing3", });
    internal_static_protoBuff_MensagemPong1_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protoBuff_MensagemPong1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoBuff_MensagemPong1_descriptor,
        new java.lang.String[] { "MensagemPong1", });
    internal_static_protoBuff_MensagemPong2_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_protoBuff_MensagemPong2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoBuff_MensagemPong2_descriptor,
        new java.lang.String[] { "MensagemPong2", });
    internal_static_protoBuff_MensagemPong3_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_protoBuff_MensagemPong3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoBuff_MensagemPong3_descriptor,
        new java.lang.String[] { "MensagemPong3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
